### ISSUE TITLE
Retina display

### ISSUE THREAD

**Issue by henryiii** [fredokun/TikZ-Editor#6]
The current binary on Mac does not use the retina display, would it be possible to fix that?

**Comment by MartinNowack** [comment]
This is fixed with Qt5 support.

**Comment by henryiii** [comment]
Thanks!

**Comment by henryiii** [comment]
PS: Is there a download of the new version for macOS, or a recommended way to get it?

**Comment by metorm** [comment]
I have just installed v1.0 from brew cask, but it still doesn't support retina display.
Shall I compile from the latest source?

**Comment by fredokun** [comment]
Sorry, I don't have access to a mac, you can launch the tool directly from the master, cf. issue #11

**Comment by metorm** [comment]
I succeeded in running a python3/pyQt5 version on my mac, which has perfect HiDPI support. But the app package I generated using pyinstaller failed to run ...

**Comment by metorm** [comment]
Yeah, that's exactly the way I am using.
I think you can use virtual box to run a temporary Mac OSX and pack the app.
The current Makefile cannot be run directly on my Mac, I had to modify some statements to eliminate errors.
Then I got a *.app package, but the pack just won't run, and there is no verbose information. I am not experienced to pyinstaller so I cannot debug the package.
